### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Whoswatching89** [fO-000/bluing#28]
Good afternoon everyone,

This is a first time post for me, this is probably in the wrong area but I am sick of scratching my head about it, really banging my head against the wall. No matter what tool I use be it bluescan, ESP32, another python tool such as bleak. I cannot seem to connect to BLE devices and dump their service and characteristic UUID's (what I am trying to do).

I have had some luck using an ESP32 to connect to a few beacons and doing what I said above but cannot do it with anything it else it seems.
 
Attempting the scan with bluescan:
![connection problems - Copy](https://user-images.githubusercontent.com/108240524/202915991-84843cf7-ebc3-47bc-8d59-c714a4ec386e.jpg)

I have no problem connecting from my android device to any of these BLE devices any idea what my problem is here??

Being able to connect from my phone...
![Screenshot_20221120-115317_BLE Scanner - Copy](https://user-images.githubusercontent.com/108240524/202915948-7064296c-317e-4d0d-93fb-ca9ff76cf25d.jpg)

**Comment by Whoswatching89** [comment]
Realized I needed a better adapter and solved the problem for myself.

**Comment by fO-000** [comment]
Great! This issue is not easy to reproduce on my side, so it is difficult to answer directly. Wondering which adapter you are using before and now.

**Comment by Whoswatching89** [comment]
Was using whatever adapter comes standard on OrangePI 3 lbs. Now using
panda 4! Thanks for the reply if you want any video testing or anything on
my end wouldn't mind.

Thanks!
