### ISSUE TITLE
Bare nRF51822 alternative to the micro:bit

### ISSUE THREAD

**Issue by mfalkvidd** [fO-000/bluing#29]
Can we use a bare nRF51822 instead of the micro:bit?

**Comment by fO-000** [comment]
It certainly works in theory, but the current code uses a lot of the micro:bit APIs. Hopefully, I'll have time to adapt bare nRF51822 later.

Also, you might be interested in the [btlejack](https://github.com/virtualabs/btlejack) project.

**Comment by fO-000** [comment]
@BJamin99 Thank you so much for your work!
