### ISSUE TITLE
请问下有没有相关的技术群

### ISSUE THREAD

**Issue by dsfhoewf** [fO-000/bluing#34]
如题，最近在学习研究这块，这块的资料也很少，有几个问题一直没解决，想加群进组织一起学习交流下，问下有相关的群或者联系方式吗？

**Comment by fO-000** [comment]
ㄟ( ▔, ▔ )ㄏ

**Comment by dsfhoewf** [comment]
那么能加下大佬的联系方式吗？希望一起交流下

**Comment by fO-000** [comment]
来啊来啊，联系方式发我邮箱吧 sourcell.xu@outlook.com

**Comment by dsfhoewf** [comment]
邮件已发，期待大佬好友位
